name = "QiskitQuantumInfo"
uuid = "8d55b643-9899-48dd-ae5e-3f792c55f725"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
ElectronicStructure = "f7ec468b-4310-4c77-90aa-f73697106762"
QuantumOps = "d0cc4389-ef80-471f-8a8c-dd305d114ada"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
